dist: trusty

language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

#before_script:
#  - npm install --prefix frontend/
#
script:
  - mvn clean test
#  - npm run build --prefix frontend/